[theme]
base = "light"
primaryColor = "#7030A0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F2FB"
textColor = "#1F1A26"
font = "sans serif"

[server]
maxUploadSize = 400

[browser]
gatherUsageStats = false