[theme]
base = "dark"
primaryColor = "#FF9F1C"
backgroundColor = "#07090C"
secondaryBackgroundColor = "#11151B"
textColor = "#E6E6E6"
font = "monospace"

[server]
maxUploadSize = 400

[browser]
gatherUsageStats = false
